// WebApplication1/reactjs/src/vehiclesForSale/VehiclesForSaleList.js
import * as React from 'react';
import '../styles/bootstrap.css';
import '../App.css';
import { configure, action, decorate, observable} from 'mobx';
import { observer, inject } from 'mobx-react';
import ReactPaginate from 'react-paginate';
import { Link } from 'react-router-dom';
import { Redirect } from 'react-router';

configure({ enforceActions: true });
class VehiclesForSaleList extends React.Component {
    cartNumberArray = [
        { id: 1, value: 1 },
        { id: 2, value: 2 },
        { id: 5, value: 5 },
        { id: 10, value: 10 },
        { id: 15, value: 15 },
        { id: 20, value: 20 }
    ];
   

    componentDidMount() {
        this.selectedValue = 1;
        const { VehiclesForSaleStore } = this.props;
        VehiclesForSaleStore.loadDataAsync();
        VehiclesForSaleStore.pageRedirect = false;
       
    }

    changePageNumber = (data) => {
        const { VehiclesForSaleStore } = this.props;
        let selected = data.selected;
        let offset = Math.ceil(selected + 1);
        VehiclesForSaleStore.vehiclesForSaleData.pageNumber = offset;
        VehiclesForSaleStore.loadDataAsync();
    }


  
    AddToCart = (id, vehiclemake, vehiclemodel, price, itemsInStockId, itemsInStock) => {
        
      
       
    
        const itemInStock ={
            VehicleMake:vehiclemake,
            VehicleModel:vehiclemodel,
            Price: price,
            VehiclePicture: "",
            Quantity: this.selectedValue,
            UserName: localStorage.getItem("userName"),
            VehiclesForSaleId: id
        }
      
    
     
        const newItemInStock = {
            Id: itemsInStockId,
            VehiclesForSaleId: id,
            ItemsInStock: itemsInStock - this.selectedValue
          }
       
          try{
          var i;
          for (i = 0; i < this.selectedValue; i++)
          {
        
            this.props.VehiclesForSaleStore.AddItemToCart(itemInStock);
          }
        }catch(error){
            console.log(error.Message);
        }

             this.props.VehiclesForSaleStore.UpdateItemsInStock(newItemInStock);
           
        
    }
   

    onChange = (event) =>{
        event.preventDefault();
        this.selectedValue = event.target.value;
    }


    render() {
        if (this.props.VehiclesForSaleStore.pageRedirect === true) {
            return <Redirect to='/ShoppingCartList' />
        }
        const { VehiclesForSaleStore } = this.props;
        return (
            <div>
            <div>
            <br />
            
            <Link to="/VehiclesForSaleList/Create">Create New</Link>
            <br />
            <br />
            </div>
        
            <div className="container">
                <div className="row vertical-align">
                    {VehiclesForSaleStore.vehiclesForSaleData.model.map(vehicle => (
                        <ul className="list-unstyled jumbotron" key={vehicle.id}>
                            <li>
                                <img src={"data:image/png;base64," + vehicle.vehiclePicture} width="240" height="180" alt="vehicle" />
                            </li>
                            <li>Name:&nbsp;
                   <b>{vehicle.vehicleMake}</b>
                            </li>
                            <li>Model:&nbsp;
                   <b>{vehicle.vehicleModel}</b>
                            </li>

                            <li>Price:&nbsp;
                   <b>{vehicle.price}$</b>
                            </li>
                            <li>Items In Stock:&nbsp;
                   <b>{vehicle.itemsInStock}</b>
                            </li>
                            <li>
                  <select onChange={this.onChange}>
                  {this.cartNumberArray.map(i =>(
                    <option key={i.id}>
                      {i.value}
                    </option>
                     ))}
                     </select>
                           </li>
                            <li>
                            <Link to={`/VehiclesForSaleList/Edit/${vehicle.id}`}>Edit</Link>&nbsp;&nbsp;
                            <Link to={`/VehiclesForSaleList/Delete/${vehicle.id}`}>Delete</Link>
                            </li>
                            <li>
                            <button type="submit" onClick ={() => this.AddToCart(vehicle.id, vehicle.vehicleMake,vehicle.vehicleModel,
                                vehicle.price, vehicle.itemsInStockId, vehicle.itemsInStock)}>Add To Cart</button>
                            </li>
                        </ul>
                        
                        
                    ))}
                    {VehiclesForSaleStore.status && <div>{VehiclesForSaleStore.status}</div>}
                    <ReactPaginate pageCount={Math.ceil(VehiclesForSaleStore.vehiclesForSaleData.totalCount / VehiclesForSaleStore.vehiclesForSaleData.pageSize)}
                        pageRangeDisplay={VehiclesForSaleStore.vehiclesForSaleData.pageSize}
                        onPageChange={this.changePageNumber}
                        marginPagesDisplayed={2}
                        containerClassName={"pagination"}
                        nextLabel={"next"}
                        previousLabel={"previous"}
                        breakLabel={<a href="">...</a>}
                        breakClassName={"break-me"}
                        subContainerClassName={"pages pagination"}
                        activeClassName={"active"}
                        nextClassName={"cursor"}
                        previousClassName={"cursor"}
                        pageClassName={"cursor"} />
                </div>
            </div>


          </div>

        )
    }


}
decorate(VehiclesForSaleList, {
    componentDidMount: action,
    selectedValue: observable
});

export default inject("VehiclesForSaleStore")(observer(VehiclesForSaleList));

// VehicleProject/Angular/src/app/vehiclesForSale/vehicles-for-sale-list.component.ts
import { Component, OnInit } from '@angular/core';
import { VehiclesForSale } from '../models/vehiclesForSale';
import { VehiclesForSaleService } from './vehicles-for-sale-service.component';
import { Router, ActivatedRoute } from '@angular/router';
import { DomSanitizer } from '@angular/platform-browser';
import { VehiclesForSaleModel } from '../models/vehiclesForSaleModel';
import { ShoppingCartService } from '../shoppingCart/shopping-cart-service';
import { DataSharingService } from '../dataSharingService';
import { HttpErrorResponse } from '@angular/common/http';


@Component({
  selector: 'app-vehicles-for-sale-list',
  templateUrl: './vehicles-for-sale-list.component.html',
  styleUrls: ['./vehicles-for-sale-list.component.css']
})
export class VehiclesForSaleListComponent implements OnInit {

  vehiclesForSaleList: VehiclesForSaleModel[];
  pageNumber: number = 1;
  pageSize: number;
  totalCount: number;
  isAscending: boolean = false;
  search: string = "";
  user: string;
  cartItem: any;
  id: number;
  newData: any;
  quantity: number = 2;
  cartNumber: number;
  cartNumberArray: any[] = [
    { id: 1, value: 1 },
    { id: 2, value: 2 },
    { id: 5, value: 5 },
    { id: 10, value: 10 },
    { id: 15, value: 15 },
    { id: 20, value: 20 }];
  errorMessage: string;




  constructor(private vehiclesForSaleService: VehiclesForSaleService, private shoppingCartService: ShoppingCartService, private router: Router,
    private sanitizer: DomSanitizer, private route: ActivatedRoute, private dataSharingService: DataSharingService) { }

  ngOnInit() {
    this.user = localStorage.getItem("userName");
    this.getPage(1);
    this.shoppingCartService.GetItemsFromCart().subscribe((cartData: any) => {
      this.cartNumber = cartData.cartList.length;
    })

  }

  getDecodedImage = (img: any) => {
    var imageToShow = 'data:image/png;base64,' + img;
    return this.sanitizer.bypassSecurityTrustUrl(imageToShow)
  }

  getPage = (pageNumber: number) => {

    this.vehiclesForSaleService.getVehiclesForSale(pageNumber, this.search, this.isAscending).
      subscribe((vehiclesForSaleData: VehiclesForSale) => {
        this.vehiclesForSaleList = vehiclesForSaleData.model;
        this.pageNumber = vehiclesForSaleData.pageNumber;
        this.pageSize = vehiclesForSaleData.pageSize;
        this.totalCount = vehiclesForSaleData.totalCount;
        this.isAscending = vehiclesForSaleData.isAscending;
      });

  }

  isAdmin = () => {
    if(localStorage.getItem("userName") === "Admin")
    {
      return true;
    }
    return false;
  }

  searchMake = (search: string) => {

    this.vehiclesForSaleService.getVehiclesForSale(this.getPage(this.pageNumber = 1), search, this.isAscending);

  }

  sortMake = () => {
    this.isAscending = !this.isAscending;
    this.vehiclesForSaleService.getVehiclesForSale(this.getPage(this.pageNumber), this.search, this.isAscending);
  }

  AddToCart = (id, selectList) => {
    this.vehiclesForSaleService.getVehiclesForSaleById(id).subscribe((cartData: any) => {
      this.cartItem = cartData;
      this.cartItem.vehiclePicture = ""
      this.cartItem.quantity = selectList;
      this.cartItem.userName = this.user;
      this.cartItem.VehiclesForSaleId = id;
     


      const newItemInStock = {
        Id: this.cartItem.stockId,
        VehiclesForSaleId: this.cartItem.id,
        ItemsInStock: this.cartItem.itemsInStock - selectList
      }

      var i;
      for (i = 0; i < selectList; i++) {
        this.shoppingCartService.AddItemToCart(this.cartItem).subscribe(() => {
          this.router.navigate(["/ShoppingCart"]);
        },(error: HttpErrorResponse) => {this.errorMessage = error.error, this.dataSharingService.cartNumber.next(0)});
       
      }
    
      this.vehiclesForSaleService.updateItemsInStock(newItemInStock);
     

      if (this.cartNumber === 0) {
        this.dataSharingService.cartNumber.next(selectList);
      }
      else {
        var result = +this.cartNumber + +selectList;
        this.dataSharingService.cartNumber.next(result);
      }

    });
    
  }

}

<div class="container">
  <div *ngIf="isAdmin()">
    <a routerLink="Create">Create</a>
  </div>
  &nbsp;
  <div class="row vertical-align">
    <ul class="list-unstyled jumbotron" *ngFor="let vehicle of vehiclesForSaleList| paginate : {id: 'server', itemsPerPage: pageSize, currentPage : pageNumber, totalItems: totalCount}">
      <div>
        <li>
          <img [src]="getDecodedImage(vehicle.vehiclePicture)" width="240" height="180">
        </li>
        <li>Name:&nbsp;
          <b>{{vehicle.vehicleMake}}</b>
        </li>
        <li>Model:&nbsp;
          <b>{{vehicle.vehicleModel}}</b>
        </li>
        <li>Price:&nbsp;
          <b>{{vehicle.price}}$</b>
        </li>
        <li>Items In Stock:&nbsp;
          <b>{{vehicle.itemsInStock}}</b>
        </li>
        <li>
          <select #selectList>
            <option *ngFor="let item of cartNumberArray" [value]="item.id">
              {{item.value}}
            </option>
          </select>
        </li>
        <li *ngIf="isAdmin()">
          <a [routerLink]="['Edit', vehicle.id ]">Edit</a>&nbsp;&nbsp;
          <a [routerLink]="['Delete', vehicle.id ]">Delete</a>
        </li>
        <li>
          <button (click) ="AddToCart(vehicle.id, selectList.value)">Add To Cart</button>
        </li>
      </div>
    </ul>
    <div>
      <span class="help-block" *ngIf="errorMessage">
         {{errorMessage}}
      </span>
  </div>
  </div>
  <div>
    <pagination-controls (pageChange)="getPage($event)" id="server"></pagination-controls>
  </div>
</div>
