// WebApplication1/reactjs/src/shoppingCart/CheckOut.js
import React from 'react'
import '../styles/bootstrap.css';
import { observer, inject } from 'mobx-react';
import { configure, decorate, action, observable } from 'mobx';
import { Redirect } from 'react-router'

configure({ enforceActions: true });
class CheckOut extends React.Component {

    componentDidMount() {
        const { ShoppingCartStore } = this.props;
        ShoppingCartStore.GetItemsFromCart();
        ShoppingCartStore.pageRedirect = false;
        this.user = localStorage.getItem("userName");
    }

    PlaceOrder = (e) => {
        e.preventDefault();
        this.props.ShoppingCartStore.PlaceOrder({
            itemsOrdered: this.props.ShoppingCartStore.shoppingCartData.cartList,
            totalPrice: this.props.ShoppingCartStore.shoppingCartData.result,
            userName: this.user,
            firstName: this.refs.FirstName.value,
            lastName: this.refs.LastName.value,
            Email: this.refs.LastName.value,
            adress: this.refs.Adress.value,
            cardType: this.selectedValue,
            cardNumber: this.refs.CardNumber.value
        })  
        this.refs.FirstName.value = null;
        this.refs.LastName.value = null;
        this.refs.Adress.value = null;
        this.refs.Adress.value = null;
        this.refs.CardNumber.value = null; 
      
    }
    
    

    onChange = (event) =>{
        event.preventDefault();
        this.selectedValue = event.target.value;
    }

    render() {
        if (this.props.ShoppingCartStore.pageRedirect === true) {
            return <Redirect to='/VehiclesForSaleList' />
        }
        return (
           
        <div>
         <div>
            <br />
            <br />
            {this.props.ShoppingCartStore.status && <div> {this.props.ShoppingCartStore.status}</div>}
        </div>
        <div>
            <form  onSubmit={this.PlaceOrder}>
            <div className="form-group">
                <input ref="FirstName" id="firstname" type="text" placeholder=" First Name" required maxLength="20" />
            </div>
            <div className="form-group">
                <input ref="LastName" id="lastname" type="text" placeholder="Last Name" required maxLength="20" />
            </div>
            <div className="form-group">
            <input ref="Email" id="email" type="email" placeholder="Email" required maxLength="20"/>
            </div>
            <div className="form-group">
            <input ref="Adress" id="adress" type="text"  placeholde="Adress" placeholder="Adress" required maxLength="20" />
            </div>
            <div className="form-group">
            <select id="cardtype" type="text" onChange={() => this.onChange}
              required>
              <option>
                Visa
              </option>
              <option>
                MasterCard
              </option>
              </select>
            </div>
            <div className="form-group">
            <input ref="CardNumber" id="cardnumber" type="text"  required pattern="(\d{16})" placeholder="Card Number" required/>
            </div>
                <button type="submit">Submit</button>
            </form>
        </div> 
    </div>
        )
    }
}
decorate(CheckOut, {
    componentDidMount: action,
    PlaceOrder: action,
    selectedValue: observable,
    user: observable
});
export default inject("ShoppingCartStore")(observer(CheckOut));

// VehicleProject/Angular/src/app/shoppingCart/checkout.component.ts
import { Component, OnInit } from '@angular/core';
import { ShoppingCartService } from './shopping-cart-service';
import { Router } from '@angular/router';
import { HttpErrorResponse } from '@angular/common/http';
import { DataSharingService } from '../dataSharingService';

@Component({
  selector: 'app-checkout',
  templateUrl: './checkout.component.html',
  styleUrls: ['./checkout.component.css']
})
export class CheckoutComponent implements OnInit {

  shoppingCartList: any[];
  shoppingCartTotalPrice: number;
  errorMessage: string;

  constructor(private shoppingCartService: ShoppingCartService, private router: Router, private dataSharingService: DataSharingService) { }

  ngOnInit() {
    this.shoppingCartService.GetItemsFromCart().subscribe(cartData => {
      this.shoppingCartList = cartData.cartList;
      this.shoppingCartTotalPrice = cartData.result;
    })
  }

  PlaceOrder = (firstName, lastName, Email, Adress, cardType, cardNumber) => {
    const fullOrder = {
      itemsOrdered: this.shoppingCartList,
      totalPrice: this.shoppingCartTotalPrice,
      userName: localStorage.getItem("userName"),
      firstName: firstName,
      lastName: lastName,
      Email: Email,
      adress: Adress,
      cardType: cardType,
      cardNumber: cardNumber
    }
    this.shoppingCartService.PlaceOrder(fullOrder).subscribe(() => this.router.navigate(["SuccessfulOrder"]),
    ((error: HttpErrorResponse) => this.errorMessage = error.error));
   
   
  }


}

<div>
  <form #CheckoutForm="ngForm">
    <div class="container" style="width:640px">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Check Out</h3>
        </div>
        <div class="panel-body">
          <div class="form-group" [class.has-error]="firstNameControl.invalid && firstNameControl.touched">
            <label for="firstName" class="control-label">First Name</label>
            <input id="firstname" name="firstName" [(ngModel)]="firstName" type="text" class="form-control" 
            required #firstNameControl="ngModel">
            <span class="text-danger" *ngIf="firstNameControl.invalid && firstNameControl.touched">
             First Name is required
            </span>
          </div>
          <div class="form-group" [class.has-error]="lastNameControl.invalid && lastNameControl.touched">
            <label for="lastName" class="control-label">Last Name</label>
            <input id="lastname" name="lastName" [(ngModel)]="lastName" type="text" class="form-control" [(ngModel)]="lastName"
            required #lastNameControl="ngModel">
            <span class="text-danger" *ngIf="lastNameControl.invalid && lastNameControl.touched">
              Last Name is required
             </span>
          </div>
          <div class="form-group" [class.has-error]="emailControl.invalid && emailControl.touched">
              <label for="Email" class="control-label">Email</label>
              <input id="email" name="Email" [(ngModel)]="Email" type="email" class="form-control" #emailControl="ngModel" required>
              <span class="text-danger" *ngIf="emailControl.invalid && emailControl.touched">
                Email is required
               </span>
            </div>
          <div class="form-group" [class.has-error]="adressControl.invalid && adressControl.touched">
            <label for="Adress" class="control-label">Adress</label>
            <input id="adress" name="Adress" [(ngModel)]="Adress" type="text" class="form-control" #adressControl="ngModel" required>
            <span class="text-danger" *ngIf="adressControl.invalid && adressControl.touched">
              Adress is required
             </span>
          </div>
          <div class="form-group">
            <label for="cardType" class="control-label">Card Type</label>
            <select #selectList id="cardtype" name="cardType" type="text" class="form-control"
              required>
              <option>
                Visa
              </option>
              <option>
                MasterCard
              </option>
              </select>
          </div>
          <div class="form-group" [class.has-error]="cardNumberControl.invalid && cardNumberControl.touched">
            <label for="cardNumber" class="control-label">Card Number</label>
            <input id="cardnumber" name="cardNumber" [(ngModel)]="cardNumber" type="text" class="form-control"
            required pattern="(\d{16})" #cardNumberControl="ngModel">
            <span class="text-danger" *ngIf="cardNumberControl.invalid && cardNumberControl.touched">
             Card Number is required with 16 digits
             </span>
          </div>
        </div>
        <div class="panel-footer">
          <button type="submit" class="btn btn-primary" [disabled]="CheckoutForm.invalid"
          (click)="PlaceOrder(firstName, lastName, Email, Adress, selectList.value, cardNumber)">
            Place Order
          </button>
        </div>
      </div>
    </div>
    <div>
      <span class="text-danger" *ngIf="errorMessage">
         {{errorMessage}}
      </span>
  </div>
  </form>
  </div>
