// VehicleProject/Angular/src/app/vehiclesForSale/vehicles-for-sale-create.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { NgForm } from '@angular/forms';
import { VehiclesForSaleService } from './vehicles-for-sale-service.component';
import { Router } from '@angular/router';


@Component({
  selector: 'app-vehiclesForSaleCreate',
  templateUrl: './vehicles-for-sale-create.component.html'
})
export class VehiclesForSaleCreateComponent implements OnInit {
  fileToUpload: File = null;
  vehicleFile : any;
  preview: any;
  constructor(private vehiclesForSaleService: VehiclesForSaleService, private router : Router) { }
  
  ngOnInit() { 
  }
  handleFileInput(event:any) {
   this.fileToUpload = event.target.files[0];
   if (event.target.files && event.target.files[0]) {
    var reader = new FileReader();
    reader.onload = (event:any) => {
      this.preview = event.target.result;
    }

    reader.readAsDataURL(event.target.files[0]);
  }
}
  CreateVehiclesForSale = (vehicleMake, vehicleModel, price, itemsInStock, itemsInStockId) => {
     var formData = new FormData();
     formData.append("vehicleMake", vehicleMake);
     formData.append("vehicleModel", vehicleModel);
     formData.append("price", price);
     formData.append("itemsInStockId", itemsInStockId);
     formData.append("itemsInStock", itemsInStock);
     formData.append(this.fileToUpload.name, this.fileToUpload);
     this.vehiclesForSaleService.createVehiclesForSale(formData).subscribe((data) => this.router.navigate(["/VehiclesForSaleList"]));
     
  }
 
}

<div>
  <form>
    <div class="container" style="width:640px">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Create</h3>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <label for="vehicleMake" class="control-label">Vehicle Name</label>
            <input id="vehiclemake" name="vehicleMake" [(ngModel)]="vehicleMake" type="text" class="form-control" 
            required>
          </div>
          <div class="form-group">
            <label for="vehicleModel" class="control-label">Vehicle Model</label>
            <input id="vehiclemodel" name="vehicleModel" [(ngModel)]="vehicleModel" type="text" class="form-control">
            
          </div>
          <div class="form-group">
            <label for="picture" class="control-label">Picture</label>
            <input id="pic" name="picture" type="file" class="form-control"
             (change) ="handleFileInput($event)">
           <img *ngIf="preview" [src]="preview" width="240" height="180">
          </div>
          <div class="form-group">
            <label for="price" class="control-label">Price</label>
            <input id="Price" name="price" [(ngModel)]="price" type="text" class="form-control"
              required>
          </div>
          <div class="form-group" >
            <label for="itemsInStockId" class="control-label">Items In Stock Id</label>
            <input id="itemsinstockid" name="itemsInStockId" [(ngModel)]="itemsInStockId" type="text" class="form-control"
            required>
          </div>
          <div class="form-group" >
            <label for="itemsInStock" class="control-label">Items In Stock</label>
            <input id="itemsinstock" name="itemsInStock" [(ngModel)]="itemsInStock" type="text" class="form-control"
            required>
          </div>
        </div>
        <div class="panel-footer">
          <button type="submit" class="btn btn-primary" (click)="CreateVehiclesForSale(vehicleMake, vehicleModel, price, itemsInStock, itemsInStockId)">Save</button>
        </div>
      </div>
    </div>
  </form>
  </div>

// WebApplication1/reactjs/src/vehiclesForSale/VehiclesForSaleCreate.js
import React from 'react'
import '../styles/bootstrap.css';
import { observer, inject } from 'mobx-react';
import { configure, decorate, action,  runInAction, observable  } from 'mobx';
import { Redirect } from 'react-router'

configure({ enforceActions: true });
class VehiclesForSaleCreate extends React.Component{
  
    AddVehiclesForSale = (e) => {
        e.preventDefault();
        var formData = new FormData();
        formData.append("vehicleMake", this.refs.VehicleMake.value);
        formData.append("vehicleModel", this.refs.VehicleModel.value);
        formData.append("price", this.refs.Price.value);
        formData.append("itemsInStockId", this.refs.ItemsInStockId.value);
        formData.append("itemsInStock", this.refs.ItemsInStock.value);
        formData.append(this.fileToUpload.name, this.fileToUpload);
        
        this.refs.VehicleMake.value = null;
        this.refs.VehicleModel.value = null;
        this.refs.Price.value = null;
        this.refs.ItemsInStockId.value = null;
        this.refs.ItemsInStock.value = null;


        this.props.VehiclesForSaleStore.CreateVehiclesForSale(formData);

        
    };


    handleFileInput = (event) => {
        event.preventDefault();
        this.fileToUpload = event.target.files[0];
        if (event.target.files && event.target.files[0]) {
         var reader = new FileReader();
         reader.onload = (event) => {
            runInAction(() => {
                this.preview = event.target.result;
            });
          
         }
     
         reader.readAsDataURL(event.target.files[0]);
      
       }
    }
  

render(){
    if (this.props.VehiclesForSaleStore.pageRedirect === true) {
        return <Redirect to='/VehiclesForSaleList' />
    }
    return(
      
        <div>
        <div>
            <h4>Create New</h4>
            <br />
            <br />
            {this.props.VehiclesForSaleStore.status === "error" && <h3> Something went wrong</h3>}
        </div>
        <div>
            <form  onSubmit={this.AddVehiclesForSale}>
            <div className="form-group">
                <input ref="VehicleMake" id="vehiclemake" type="text" placeholder=" Vehicle Name" required maxLength="20" />
            </div>
            <div className="form-group">
                <input ref="VehicleModel" id="vehiclemodel" type="text" placeholder="Vehicle Model" required maxLength="20" />
            </div>
            <div className="form-group">
            <input ref="VehiclePicture" id="vehiclepicture" onChange={this.handleFileInput} type="file" accept="image/*" required/>
            {this.preview && <img src={this.preview} alt="vehicle" width="240" height="180"/>}
            </div>
            <div className="form-group">
            <input ref="Price" id="price" type="text"  placeholde="Price" placeholder="Price" required/>
            </div>
            <div className="form-group">
            <input ref="ItemsInStockId" id="itemsinstockid" type="text"  placeholder="Items In Stock Id" required/>
            </div>
            <div className="form-group">
            <input ref="ItemsInStock" id="itemsinstock" type="text"  placeholder="Items In Stock" required/>
            </div>
                <button type="submit">Save</button>
            </form>


        </div>
    </div>

    )
}
}
decorate(VehiclesForSaleCreate, {
    AddVehiclesForSale: action,
    preview: observable
    
});
export default inject("VehiclesForSaleStore")(observer(VehiclesForSaleCreate));
